
name: cowpy exmaple

on:
  push:

jobs:
  install-cowpy:
    runs-on: ubuntu-latest
    steps:
    - name: install-cowpy
      run: pip install cowpy
    - name: run-cowpy-cmd
      run: cowpy -c tux hi there
    - name: run-cowpy-script
      working-directory: ./../scripts
      run: python3 cow.py