
name: cowpy exmaple

on:
  push:

jobs:
  install-cowpy:
    runs-on: ubuntu-latest
    steps:
    - name: install-cowpy
      run: pip install cowpy
    - name: run-cowpy-cmd
      run: cowpy -c tux hi there
    - name: clone-repo
      run: |
       git clone https://github.com/NicholasCowie/dsp_actions_tutorial.git
       cd dsp_actions_tutorial/scripts
       python3 cow.py
